### ISSUE TITLE
clean_content_views key error for id

### ISSUE THREAD

**Issue by linuxabides** [RedHatSatellite/sat6_scripts#49]
# Behavior:
[user@satellite ~]# clean_content_views
Cleaning content view 'Server'
Removing version 1.0
Traceback (most recent call last):
  File "/usr/share/sat6_scripts/bin/clean_content_views", line 7, in <module>
    clean_content_views.main(sys.argv[1:])
  File "/usr/share/sat6_scripts/clean_content_views.py", line 291, in main
    cleanup(ver_list, ver_descr, dry_run, runuser, ver_keep, cleanall, ignorefirstpromoted)
  File "/usr/share/sat6_scripts/clean_content_views.py", line 201, in cleanup
    ))['id']
KeyError: 'id'
[user@satellite ~]# clean_content_views -d
Cleaning content view 'Server'
Removing version 1.0
Removing version 1.1
Removing version 1.2
Skipping delete of version 2.0 due to --keep value
WARNING: Dry run - not actually performing removal

# Config:
/usr/share/sat6_scripts/config/config.yml
cleanup:
  content_views:
    - view: Server
      keep: 1

# Info:
sat6_scripts on version 1.2.3 commit 6889caf3840d4649d3a9bd00218c31ca061ace78
satellite-6.3.2-1.el7sat.noarch
PyYAML-3.10-11.el7.x86_64

Same result with:
  clean_content_views -a -d

**Comment by ggatward** [comment]
This looks similar to what we had in #29 - it was not reproducible on demand and seemed quite random as to when the API response was null.  I have added some exception handling to clean_content_views.py (currently in the development branch) that will avoid the backtrace, but not sure how to get to the root of this issue....  I can't repoduce this exception here (Sat 6.3.3)

Is this reproducible every time on your setup?

**Comment by linuxabides** [comment]
We have upgraded to Sat 6.4.
Info: satellite-6.4.0-15.el7sat.noarch
Commit: 3879f0e64143b2e80a2df7263a0e3abb863f003b
Result is Fail (same)

Additional Info:
Are you testing with the removal of incremental published content versions?

**Comment by linuxabides** [comment]
Can confirm works when only removing major CV versions.
Does not work when removing incremental versions of CVs.

**Comment by ggatward** [comment]
Awesome - thanks for that. I have only been testing with major versions, will look into the incremental CV version problem.

**Comment by linuxabides** [comment]
Also same error when trying to remove content view that is currently being used in a composite content view.

**Comment by ggatward** [comment]
Hi @linuxabides - Been reviewing the code around the deletions today - could you try with the -i (ignorefirstpromoted) flag?  i.e.  clean_content_views -d -i  ?    I have a feeling that this may alreday be 'fixed' by using this flag, as the calculation of views to delete is based on a number in the array rather than mathematically (which is the root case of the problem - I am subtracting integer 1 from the last CV so it ignores all the sub-versions).  If -i works for you I might make it the default method and remove the broken one that only deals in .0 releases....

**Comment by arusso** [comment]
Also on Satellite 6.4 and I've been running into this same issue. The `-i` flag didn't change the behavior for me. I ended up patching the script to just skip those for now:

```
$ diff clean_content_views.py clean_content_views.py.modified
194c194
<                         task_id = helpers.put_json(
---
>                         resp = helpers.put_json(
201c201,212
<                                 ))['id']
---
>                                 ))
>                         if 'id' in resp.keys():
>                             task_id = resp['id']
>                         elif 'in use by composite content views' in resp['displayMessage']:
>                             msg = "Skipping delete of version " + str(version['version']) + " due to being in use by one or more CCV"
>                             helpers.log_msg(msg, 'INFO')
>                             print msg
>                             continue
>                         else:
>                             msg = "Failed"
>                             helpers.log_msg(msg, 'ERROR: ')
>                             print msg
```

It's an admittedly crude fix, so I'd be happy to test whatever fix you propose.

**Comment by arusso** [comment]
I tested with the version in master. Using ISSUE-49 branch, that solves the immediate issue of the script prematurely crashing when it encounters an issue -- including trying to delete a CV that's part of a CVV. Though, it would be nice to indicate why the failure occurred to the user in this particular case.

```
[root@sat-server-01 sat6_scripts]# ./clean_content_views.py -o 1 -k 3  -c -a
Cleaning content view 'cv-app-render'
Cleaning content view 'cv-app-satellite-tools'
Removing version 45.0
WARNING: Failed to initiate removal
```

**Comment by arusso** [comment]
Seems like the `-k 3` flag was being ignored now in the above command -- all the unused content views were removed rather than keeping the newest 3 versions. Before pulling this change in it was being honored.

**Comment by ggatward** [comment]
I suspect that was previously also a bug :-( the Cleanall option was supposed to delete ALL orphan versions regardless of the -k flag. I think in the work done recently in this code that issue was also fixed.  During testing I documented the behaviour of the various flags, which is now in the README of the ISSUE-49 branch, and is below using a keep value of 1....
`+-----------------+----------+-----------------------+------------+
| version         | no flags | --ignorefirstpromoted | --cleanall |
+-----------------+----------+-----------------------+------------+
| 110.0 (Library) |          |                       |            |
| 109.0           |   KEEP   |         KEEP          |    DEL     |
| 108.3           |   KEEP   |         DEL           |    DEL     |
| 108.2 (Quality) |          |                       |            |    
| 108.1           |   KEEP   |         DEL           |    DEL     |
| 108.0           |   DEL    |         DEL           |    DEL     |
| 107.0           |   DEL    |         DEL           |    DEL     |
+-----------------+----------+-----------------------+------------+`
I suspect that the 'default' behaviour with no flags is what you are looking for now, so  -o1 -k3 -a  should do what you are looking for - the -c overrides -k...  I probably need to clarify that behaviour better in the doc though....

I also need to check what happens with a CCV, but I am hoping that the standard CV use case is working now with this version

**Comment by arusso** [comment]
ah that makes sense. I think I was confusing `-c` with `-a` a bit as well.

**Comment by ggatward** [comment]
I believe I have found the issues around versions in CCV.  Latest commit  https://github.com/RedHatSatellite/sat6_scripts/commit/dededcb5df7f4c11c0d2c5dfe13d4a5f75dcfa31 in ISSUE-49 branch should do the trick.  Will merge this up to development and master on the weekend if no further issues here.

**Comment by linuxabides** [comment]
> I believe I have found the issues around versions in CCV. Latest commit [dededcb](https://github.com/RedHatSatellite/sat6_scripts/commit/dededcb5df7f4c11c0d2c5dfe13d4a5f75dcfa31) in ISSUE-49 branch should do the trick. Will merge this up to development and master on the weekend if no further issues here.

This commit fixed my issues.
